apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: meldekort-mikrofrontend
  namespace: meldekort
  labels:
    team: meldekort
spec:
  image: {{ image }}
  port: 7800
  liveness:
    path: /meldekort-mikrofrontend/internal/isAlive
    initialDelay: 10
  readiness:
    path: /meldekort-mikrofrontend/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /meldekort-mikrofrontend/internal/metrics
  replicas:
    min: 2
    max: 4
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: "500m"
      memory: 128Mi
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  tokenx:
    enabled: true
  env:
    - name: MELDEKORT_API_AUDIENCE
      value: "{{meldekortApiAudience}}"
    - name: MELDEKORT_API_URL
      value: "{{meldekortApiUrl}}"
    - name: MELDEKORTREGISTER_AUDIENCE
      value: "{{meldekortregisterAudience}}"
    - name: MELDEKORTREGISTER_URL
      value: "{{meldekortregisterUrl}}"
  accessPolicy:
    outbound:
      rules:
        - application: {{meldekortApiName}}
        - application: dp-meldekortregister
          namespace: teamdagpenger
